### ISSUE TITLE
Firefox looks like it doesn't work, but it mostly does

### ISSUE THREAD

**Issue by whitty** [arktiv/table-csv-chrome#4]
Steps to reproduce:

1. Add extension to firefox (versions 76, 77 tested)
2. Visit https://www.w3schools.com/html/html_tables.asp
3. Don't click anywhere - if you do return to this start by hitting F5 (refresh)
4. Right-click in the example company table
5. Choose Download Table as CSV

Expected results:

Extension should offer to download the table

Actual results:

No effect.

I've looked into this issue and it seems like the caret is not placed in Firefox until you start navigating in the file.  The `focusNode` returns as null/undefined, terminating the content script on dereference.

I'm putting up a pull request to highlight the issue by telling the user how to work around it. It's not great, but it makes the whole thing look less broken.

Workaround

1. Click anywhere in the table (to set the caret on the table)
2. proceed from step 4 above

**Comment by arktiv** [comment]
Thanks for all the investigation you've done here, saved me a lot of effort!
I have come up with a nasty hack to solve the problem, I'm sure I'll regret it later. In the process I made a few other changes that differed from the Chrome version so have uploaded it as a separate repo here: https://github.com/arktiv/table-csv-firefox

I have also added you as a collaborator on the Firefox fork as I have little time to work on it myself, but feel free to ignore it of course.
